### ISSUE TITLE
Epic | Reduce Tchap specific source code

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#663]
Following #636, there is still Tchap specific code for those parts :
- [ ] Authentication / Account creation
- [ ] Change Password / Forgot Password
- [ ] Account Validity
- [ ] Password Policy
- [ ] App version checker
- [ ] Favorites Messages -> to be removed by a specific PR (Tchap will wait for Element implementation on favorite messages if any)
- [ ] Public Rooms
- [ ] Room Creation
- [ ] Room Preview (Used by Public Rooms)
- [ ] 3PID (Used by UserService)
- [ ] Media Service (Used by Room Creation)
- [ ] Invite by email
- [ ] Identity Service
- [ ] Home Server selection
- [ ] Display Name

**Comment by giomfo** [comment]
@phlniji you may have a look on this pending issue
you may start by checking the RoomsListViewController in RiotShareExtension (see my comment [here](https://github.com/tchapgouv/tchap-ios/pull/721#pullrequestreview-1269652077))

**Comment by phlniji** [comment]
The RoomsListViewController has been updated in this PR #723 
I will check the other parts.
