### ISSUE TITLE
Lorsque je desactive les notifications sur mon appareil, je ne peux plus recevoir d'appel

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#975]
## why
User story : Je veux désactiver les notifications de mon téléphone mais continuer à recevoir des appels

## what

Actuellement, si on desactive les "notifications sur cet appareil" , les appels ne sont plus déclenché sur le téléphone.

![IMG_71DB72B75A2D-1](https://github.com/tchapgouv/tchap-ios/assets/4077729/5a24bf9d-c273-43ac-bfa0-62354f63803d)

Les appels VoIP étant déclenchés par notifications, si l'utilisateur désactive les notifications dans Tchap, il ne sera plus notifié d'appel VoIP en cours.

NB Sur whatsapp et signal, desactiver les notifications ne desactivent les appels entrants.

## how : 

```[tasklist]
### Tasks
- [x] mettre à jour la documentation pour bien expliquer ce cas : https://aide.tchap.beta.gouv.fr/fr/article/tester-les-appels-audio-dans-tchap-6tk886/
- [ ] investiguer si on peut laisser passer les notifications voip coté sygnal (mais elles sont chiffrées il me semble)
- [ ] idée : changer l'intitulé de "notifications sur cet appareil ON/OFF", par exemple en "ne pas déranger ON/OFF"
- [ ] A-t-on le meme comportement sur Android? @yostyle
- [ ] a t on le meme comportement en dev ?
- [ ] sur web, on peut desactiver les notifications desktop tout en continuant à recevoir des appels
```

## autre cas

De même s'il configure son iPhone en mode "Concentration" masquant les notification (https://support.apple.com/fr-fr/guide/iphone/iphd6288a67f/ios), les appels entrants ne seront plus signalés.

**Comment by NicolasBuquet** [comment]
La discussion existe aussi chez Signal : https://github.com/signalapp/Signal-iOS/issues/983

Point a fouiller : interaction entre CallKit et le mode DoNotDisturb

**Comment by NicolasBuquet** [comment]
Une première info intéressante : https://stackoverflow.com/questions/66344255/how-to-show-incoming-callkit-window-for-voip-push-call-even-if-the-device-do-no

> When do-not-disturb is active, WhatsApp doesn't display a notification after receiving an audio call, it only displays notifications for video calls. That's because they use CallKit and PushKit only for audio calls. For video calls they use normal push notifications.

**Comment by odelcroi** [comment]
Cas de test : 
Test A
- j'active les notification dans Tchap "Notifications sur cet appareil : ON"
- je ferme l'application
- je n'active aucune notification dans les parametres de l'app (voir screenshot)
- j'appel depuis un autre compte depuis le client web
- l'appel entrant n'est pas notifié
![IMG_EA2949B4246A-1](https://github.com/tchapgouv/tchap-ios/assets/4077729/ef03cd07-6d13-474b-8d80-98392559f7dc)

Test B
- j'active les notification dans Tchap "Notifications sur cet appareil : ON"
- je ferme l'application
- j'active un parametre : "Ecran vérouillé" ou "Centre de notifications" ou "Bannières"
- j'appel depuis un autre compte depuis le client web
- l'appel entrant est notifié
![IMG_ED20611D7449-1](https://github.com/tchapgouv/tchap-ios/assets/4077729/12a52e91-23d7-4f98-9347-5dbd8c968bc4)

**Comment by NicolasBuquet** [comment]
> Cas de test : Test A
> 
>     * j'active les notification dans Tchap "Notifications sur cet appareil : ON"
> 
>     * je ferme l'application
> 
>     * je n'active aucune notification dans les parametres de l'app (voir screenshot)
> 
>     * j'appel depuis un autre compte depuis le client web
> 
>     * l'appel entrant n'est pas notifié
>       ![IMG_EA2949B4246A-1](https://private-user-images.githubusercontent.com/4077729/308578283-ef03cd07-6d13-474b-8d80-98392559f7dc.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDQ1NzYsIm5iZiI6MTcwOTE0NDI3NiwicGF0aCI6Ii80MDc3NzI5LzMwODU3ODI4My1lZjAzY2QwNy02ZDEzLTQ3NGItOGQ4MC05ODM5MjU1OWY3ZGMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE4MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDE4YWMyYzM1YzJkZjdmYmY2ZTIzMjRlM2Y3ZTc5ZjgwYzAzY2I0OWNiZDM0NzA5OTc5MjEzYTA5Njg3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wz32Y-uxSv-_AY-Zz3bf6Ocmk8wiUa0rKeITqUuN9ug)
> 
> 
> Test B
> 
>     * j'active les notification dans Tchap "Notifications sur cet appareil : ON"
> 
>     * je ferme l'application
> 
>     * j'active un parametre : "Ecran vérouillé" ou "Centre de notifications" ou "Bannières"
> 
>     * j'appel depuis un autre compte depuis le client web
> 
>     * l'appel entrant est notifié
>       ![IMG_ED20611D7449-1](https://private-user-images.githubusercontent.com/4077729/308578688-12a52e91-23d7-4f98-9347-5dbd8c968bc4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDQ1NzYsIm5iZiI6MTcwOTE0NDI3NiwicGF0aCI6Ii80MDc3NzI5LzMwODU3ODY4OC0xMmE1MmU5MS0yM2Q3LTRmOTgtOTM0Ny01ZGJkOGM5NjhiYzQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE4MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMTRkNGQ1ZDhkOTgxM2NkYTJiYTFjNDVhOWIzZWIzYzg4MDc2YWIwYzk5ZjExN2UxMTMxMjFmMmJiZTZkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZWYZm6z7Qc5A6GM0b9g-G_2q1e0JVyP2s66F07etMD4)

@odelcroi 
Ça c'est un bug connu sur iOS : si aucun mode d'affichage de notification n'est sélectionné dans le reglage système des notifications iOS, les notifications n'atteignent pas l'application ni même le système.

Le ticket : https://github.com/tchapgouv/tchap-ios/issues/803

**Comment by NicolasBuquet** [comment]
@odelcroi 
Proposition 
![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/6fb5aa97-76e5-4f0f-bdae-57a3281ad840)

**Comment by odelcroi** [comment]
@areox-net

**Comment by areox-net** [comment]
Je trouve la solution proposée bonne. Je sugere juste de reduire le texte en bas du réglages:

`Si cette option est désactivée, les appels entrants ne seront pas notifiés.`

**Comment by NicolasBuquet** [comment]
@areox-net 
![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/b5d00b97-d951-46a7-b7ed-66362673b86a)

**Comment by areox-net** [comment]
Ok pour moi !
